"""Mask construction and apodization for ACT and Planck."""
import numpy as np
from pixell import enmap
from pspy import so_map

import pipeline_config as cfg
from map_loader import load_npipe_mask
from tools.data_loading import act_window_path
from tools.masks import compute_fsky, get_act_analysis_window



def build_window_tuple(mask_apodized):
    """Build the (T_window, P_window) tuple expected by pspy.

    Args:
        mask_apodized: Apodized mask (so_map).

    Returns:
        Tuple (window_T, window_P) for use with pspy MCM functions.
    """
    return (mask_apodized, mask_apodized)




# ============================================================
# NPIPE (HEALPix) window functions
# ============================================================

def get_npipe_cross_window(npipe_freq, window_type="baseline"):
    """Get window for NPIPE maps in ACT x NPIPE cross-spectra.

    Uses the combined ACT + Planck point source window
    (cfg.NPIPE_ACT_WINDOW_WITH_PS), which is the ACT baseline window
    multiplied by the Planck PS mask. Generated by
    data/masks/make_npipe_act_window.py.

    Falls back to the plain ACT window if the combined file is missing.

    Args:
        npipe_freq: NPIPE frequency in GHz (100, 143, 217, 353)
        window_type: "baseline" (default)

    Returns:
        Tuple (window_T, window_P), f_sky
    """
    combined_path = cfg.NPIPE_ACT_WINDOW_WITH_PS
    window = so_map.read_map(combined_path)
    fsky = compute_fsky(window)
    return (window, window), fsky




def get_npipe_analysis_window(nside):
    """Load NPIPE mask for power spectrum analysis.

    Args:
        nside: HEALPix resolution (1024 or 2048). Required.

    Returns:
        Tuple (window_T, window_P), f_sky

    Note: The NPIPE mask is already apodized, so we don't apply
    additional apodization.
    """
    mask = load_npipe_mask(nside=nside)

    # Mask is already apodized - use as-is
    # Compute fsky
    fsky = compute_fsky(mask)

    # Build window tuple
    win_tuple = build_window_tuple(mask)

    return win_tuple, fsky
