"""Configuration for the ACT/Planck power spectrum pipeline."""
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from tools.data_loading import (
    OUTPUT_DIR, PUBLISHED_ACT_DIR, ACT_N_SPLITS,
    ACT_MASK_SUBDIR, JOINT_SUBDIR,
)
from tools.binning import get_unified_binning_file

# ============================================================
# ACT array-band definitions
# ============================================================

ACT_ARRAY_BANDS = ["pa4_f220", "pa5_f090", "pa5_f150", "pa6_f090", "pa6_f150"]

# ============================================================
# NPIPE configuration
# ============================================================

NPIPE_FREQS = [30, 44, 70, 100, 143, 217, 353]
NPIPE_SPLITS = ["A", "B"]
NPIPE_NSIDE = {30: 1024, 44: 1024, 70: 1024, 100: 2048, 143: 2048, 217: 2048, 353: 2048}
NPIPE_MASK_PERCENT = 30

# Number of parallel workers for NPIPE×NPIPE NaMaster spectrum computation.
# Each worker runs one independent spectrum. Set to 1 for sequential.
NPIPE_NWORKERS = 32

# ACT window used for all NPIPE maps in ACT x NPIPE cross-spectra.
# ACT bands share the same W_Galactic and W_sources masks; only W_edges
# (a ~0.5 deg strip at scan boundaries) differs per band, making the
# choice of which ACT window to reuse for Planck inconsequential.
NPIPE_ACT_WINDOW = "pa5_f090"

# Combined ACT + Planck point source window for NPIPE on ACT footprint.
# Generated by data/masks/make_npipe_act_window.py.
NPIPE_ACT_WINDOW_WITH_PS = os.path.join(
    os.path.dirname(os.path.dirname(__file__)),
    "data", "masks", "npipe_act_window_with_ps.fits"
)


# ============================================================
# Multipole ranges — computation (MCM/alm ceiling)
# ============================================================

# Computation lmax: sets the MCM and alm transform ceiling.
# These are NOT the analysis ell ranges (see beta_mcmc/config.py for those).
ACT_X_ACT_COMPUTE_LMAX = 8500
ACT_X_NPIPE_COMPUTE_LMAX = 2200
NPIPE_COMPUTE_LMAX = 2200

ACT_X_NPIPE_NITER = 0

# ============================================================
# K-space filter configuration
# ============================================================

APPLY_KSPACE_FILTER = True
KSPACE_FILTER_DICT = {"type": "binary_cross", "vk_mask": [-90, 90], "hk_mask": [-50, 50], "weighted": False}

# ============================================================
# Output subdirectories
# ============================================================

NPIPE_MASK_SUBDIR = "npipe_full_sky_mask" if NPIPE_MASK_PERCENT == 0 else f"npipe_{NPIPE_MASK_PERCENT}_mask"

# ============================================================
# Spectrum types to compute
# ============================================================

COMPUTE_ACT_MASK = True    # ACT×ACT + ACT×NPIPE + NPIPE×NPIPE(ACT mask)
COMPUTE_ACT_X_ACT_ONLY = False  # Only run ACT×ACT, skip ACT×NPIPE and NPIPE×NPIPE
COMPUTE_NPIPE_FULL_SKY_MASK = True   # NPIPE×NPIPE (NPIPE mask, controlled by NPIPE_MASK_PERCENT)

SPECTRA_OF_INTEREST = ["TT", "TE", "TB", "ET", "BT", "EE", "EB", "BE", "BB"]

